KS-lesson2-4 ore bonus buff
JohnnyGomezzz/KotlinSprint pull request #10
Opened 2024-10-06 08:57 UTC by JohnnyGomezzz

2024-10-06 19:10 UTC, ievetrovdev requested changes

2024-10-06 19:10 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task4.kt
> +    val minerBuff = 0.2F
Для возможности гибкой работы с кодом, следует инициализировать согласно ТЗ проценты целым числом 20. И уже потом производить вычисление процентов. Таким образом, если нужен будет другой процент, достаточно будет поменять значение в одном месте.

2024-10-07 17:04 UTC, ievetrovdev requested changes

2024-10-07 17:04 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task4.kt
> +    val bonusCrystalOre = crystalOre * minerBuff / 100
“Голые” числа в коде называются [магические числа](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования). Не является хорошей практикой. Предлагаю вынести в переменную, чтобы можно было легко в одном месте поменять характеристики бафа

2024-10-07 17:27 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson2/lesson2_task4.kt
> +    val bonusCrystalOre = crystalOre * minerBuff / 100
В формуле поправил, а тут запамятовал...

2024-10-07 19:19 UTC, ievetrovdev approved these changes

2024-10-07 19:37 UTC, merged