KS-20-3 lambda list done?
JohnnyGomezzz/KotlinSprint pull request #102
Opened 2024-11-07 13:10 UTC by JohnnyGomezzz

2024-11-07 13:12 UTC, JohnnyGomezzz commented
Вроде и нормально всё, а вроде и криво... Идея упорно предлагает сократить. По идее мап и так принимает лямбду?

2024-11-07 13:49 UTC, ievetrovdev requested changes

2024-11-07 13:49 UTC, ievetrovdev commented on src/main/kotlin/lesson20/lesson20_task4.kt
> +    val listOfButtons: List<String> = listOf(
Для теста так можно, но если не нравится можешь сгенерировать список)

2024-11-07 13:49 UTC, ievetrovdev commented on src/main/kotlin/lesson20/lesson20_task4.kt
> +        if (listOfButtons.indexOf(it) % 2 == 0) { it: String -> println("Нажат элемент $it") }(it)
Такой способ не самый эффективный, indexOf под капотом проходит весь списк, как и map, получается вложенные циклы, которые стоит избегать.
Сделай сначала преобразование(map) в лямбду, а потом уже вывод четных элементов

2024-11-07 13:50 UTC, ievetrovdev commented
И будь внимательнее с название ПР, по нему 20-3, а по факту 20-4

2024-11-08 06:51 UTC, ievetrovdev approved these changes

2024-11-08 12:24 UTC, merged