KS-3-4-players-created-moves
JohnnyGomezzz/KotlinSprint pull request #16
Opened 2024-10-07 12:50 UTC by JohnnyGomezzz

2024-10-07 19:24 UTC, ievetrovdev requested changes

2024-10-07 19:24 UTC, ievetrovdev commented on src/main/kotlin/lesson3/lesson3_task4.kt
> +                    "%s, %s: %s-%s; %s",
Обращаю внимание на пример строки для отправки на сервер [откуда-куда;номер хода]
В условии не случайно уточнен выводимый формат. Если формат готовой строки будет отличаться, то сервер не сможет ее распарсить и программа может упасть/не работать итд.
Предлагаю привести формат в соответствие с форматов в ТЗ)

2024-10-07 19:24 UTC, ievetrovdev commented on src/main/kotlin/lesson3/lesson3_task4.kt
> +    class Player(name: String, color: String) {
Создание класса и объекта не целесообразно для данной задачи)

2024-10-07 19:38 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson3/lesson3_task4.kt
> +    class Player(name: String, color: String) {
Психанул...)

2024-10-08 17:51 UTC, ievetrovdev approved these changes

2024-10-08 17:52 UTC, merged