KS-6-2-timer-done
JohnnyGomezzz/KotlinSprint pull request #29
Opened 2024-10-16 10:31 UTC by JohnnyGomezzz

2024-10-16 14:13 UTC, ievetrovdev requested changes

2024-10-16 14:13 UTC, ievetrovdev commented on src/main/kotlin/lesson6/lesson6_task2.kt
> +    while (totalSeconds != counter) {
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2024-10-16 14:26 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson6/lesson6_task2.kt
> +    while (totalSeconds != counter) {
Задачка с подвохом))

2024-10-17 06:27 UTC, ievetrovdev commented on src/main/kotlin/lesson6/lesson6_task2.kt
> +    while (totalSeconds != counter) {
Чуть-чуть)

2024-10-17 06:27 UTC, ievetrovdev approved these changes

2024-10-17 09:04 UTC, merged