KS_lesson1-3 Gagarin's flight
JohnnyGomezzz/KotlinSprint pull request #3
Opened 2024-10-04 14:40 UTC by JohnnyGomezzz

2024-10-05 05:32 UTC, ievetrovdev requested changes
Я оставил комментарий для доработки. чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-10-05 05:32 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task3.kt
> +//    println("Время взлёта:")
В целом результат есть! но в примере в ТЗ цифры начинаются с 0. А ты просто закомментировал вывод. И не стоит просто так оставлять закомментированный код
Вообще нормальная практика, если сервер присылает дату или время строкой.
Давай объявим строки и сделаем правильный формат)

2024-10-05 07:22 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson1/lesson1_task3.kt
> +//    println("Время взлёта:")
Неверно понял задание, поэтому сначала вывел, а потом закомментил))

2024-10-05 12:57 UTC, ievetrovdev requested changes

2024-10-05 12:57 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task3.kt
> +    print("0")
Не просто так намекал на строку, такой вывод не самый лучший. Ведь если время будет например 11, то вывод сломается. Поэтому лучше сделать время сразу строкой и записывать "09"

2024-10-06 06:43 UTC, ievetrovdev approved these changes

2024-10-06 07:06 UTC, merged