KS-8-2-ingredients-check-done
JohnnyGomezzz/KotlinSprint pull request #39
Opened 2024-10-18 10:56 UTC by JohnnyGomezzz

2024-10-18 12:40 UTC, JohnnyGomezzz commented
Случайно запульнул 3 задачу сюда...

2024-10-18 18:57 UTC, ievetrovdev requested changes

2024-10-18 18:57 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task2.kt
> +    for (i in ingredientsOfSoup.indices) {
Можно обойтись без обращения к индексам. А проходить по массиву просто через in и в i будет передаваться каждый элемент для сравнения.

2024-10-18 18:57 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task2.kt
> +            println("Такого ингредиента в рецепте нет")
Сообщение, что рецепта нет лучше вынести за пределы цикла. Потому, что когда мы находим ингредиент мы выходим из цикла

2024-10-18 18:58 UTC, ievetrovdev commented
> Случайно запульнул 3 задачу сюда...

Ок, в данном пулл реквесте надо:
- переключиться в ветку текущего ПР
- удалить лишний файл с задачей (физически из проекта)
- закоммитить

2024-10-19 19:11 UTC, ievetrovdev approved these changes

2024-10-20 04:51 UTC, merged