KS-8-4-ingredient-changed
JohnnyGomezzz/KotlinSprint pull request #41
Opened 2024-10-18 13:15 UTC by JohnnyGomezzz

2024-10-18 19:08 UTC, ievetrovdev requested changes

2024-10-18 19:08 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task4.kt
> +        if (!ingredientsOfSoup.contains(changeableIngredient)) {
Конструкции `ingredientsOfSoup.contains(changeableIngredient)` и `ingredientsOfSoup.indexOf(changeableIngredient)` внутри себя осуществляют проход по всему списку циклом. То есть, ты два раза делаешь перебор всех элементов цикла. Можно оптимизировать, сделав за if-ом `indexOf`, сохранить в переменную и делать сравнение с `-1` (это то, что возвращает `indexOf` если ничего не нашел). А далее использовать тот же индекс для замены ингредиента

2024-10-19 07:38 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson8/lesson8_task4.kt
> +        if (!ingredientsOfSoup.contains(changeableIngredient)) {
Не знал про -1... Надо внимательнее курить мануалы)

2024-10-19 19:14 UTC, ievetrovdev requested changes

2024-10-19 19:14 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task4.kt
> +        if (indexOfChangeableIngredient == -1) {
Все хорошо, но теперь это магическое число, не лучшая практика, предлагаю вынести в константу

2024-10-20 15:29 UTC, ievetrovdev approved these changes

2024-10-20 15:29 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task4.kt
> +const val IS_ABSENT = -1
Начинать с IS принято все же для boolean переменных, здесь бы подошло `UNKNOWN_RESULT`

2024-10-20 15:32 UTC, merged