KS-9-5-sorted-capitalized-user-list-done
JohnnyGomezzz/KotlinSprint pull request #46
Opened 2024-10-19 15:05 UTC by JohnnyGomezzz

2024-10-20 15:33 UTC, ievetrovdev requested changes

2024-10-20 15:33 UTC, ievetrovdev commented on src/main/kotlin/lesson9/lesson9_task5.kt
> +        if (ingredient in userIngredients) {
Хорошо! но теперь давай сделаем еще лучше. А именно. посмотри или вспомни какая коллекция не умеет хранить повторы?
Вот в нее можно превратить проинициализированный введенными значениями список.

2024-10-20 15:50 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson9/lesson9_task5.kt
> +        if (ingredient in userIngredients) {
Не совсем понял, просто преобразовать в Set, вот так?
Или изначально сетом делать? Но без проверки всё равно не обойтись - при заполнении повторы просто накладываются...

2024-10-22 11:51 UTC, ievetrovdev requested changes

2024-10-22 11:51 UTC, ievetrovdev commented on src/main/kotlin/lesson9/lesson9_task5.kt
> +        if (ingredient in userIngredients) {
Да, просто сделать set, ход с проверкой тоже не будет лишним, чтобы уведомить пользователя, что элемент уже есть

2024-10-22 16:00 UTC, ievetrovdev approved these changes

2024-10-22 16:02 UTC, merged