KS-9-4-sorter-completed
JohnnyGomezzz/KotlinSprint pull request #47
Opened 2024-10-19 15:09 UTC by JohnnyGomezzz

2024-10-20 05:53 UTC, JohnnyGomezzz commented
Наверное нужна проверка введённых юзером элементов, но не пойму какая...

2024-10-20 15:32 UTC, ievetrovdev requested changes

2024-10-20 15:32 UTC, ievetrovdev commented on src/main/kotlin/lesson9/lesson9_task4.kt
> +    val userIngredients = readln().split(", ")
Отлично, можно еще короче сделать без дополнительного списка, сразу применив sorted)

2024-10-20 15:35 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson9/lesson9_task4.kt
> +    val userIngredients = readln().split(", ")
Там в условии задачи "используй тот метод сортировки, который возвращает новую отсортированную коллекцию", но может я неправильно понял

2024-10-21 11:36 UTC, ievetrovdev commented on src/main/kotlin/lesson9/lesson9_task4.kt
> +    val userIngredients = readln().split(", ")
sorted как раз возвращает отсортированный список, это больше про то, что не было необходимости создавать дополнительную переменную хранящую еще один список
Сейчас все корректно!

2024-10-21 11:36 UTC, ievetrovdev approved these changes

2024-10-21 11:45 UTC, merged