KS_lesson1-5 Gagarin's flight total time
JohnnyGomezzz/KotlinSprint pull request #5
Opened 2024-10-04 16:41 UTC by JohnnyGomezzz

2024-10-05 05:34 UTC, ievetrovdev requested changes

2024-10-05 05:34 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val minutes = seconds / 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это магическое число, что тоже не является хорошей практикой.

2024-10-05 12:59 UTC, ievetrovdev requested changes

2024-10-05 12:59 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val TIME_UNITS = 60
почти правильно, и оформление, только это не константа, а обычная неизменяемая переменная. Нехватке ключевого слова const

2024-10-05 13:01 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val TIME_UNITS = 60
Я пробовал, но идея красную лампу выдаёт на const...

2024-10-05 13:54 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val TIME_UNITS = 60
Допёрло)

2024-10-06 06:44 UTC, ievetrovdev approved these changes
Да) отлично

2024-10-06 07:07 UTC, merged