KS-13-3 phonebook list created
JohnnyGomezzz/KotlinSprint pull request #66
Opened 2024-10-26 06:28 UTC by JohnnyGomezzz

2024-10-26 11:37 UTC, ievetrovdev requested changes

2024-10-26 11:37 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task3.kt
> +    phoneList.forEach { println(it.company) }
По ТЗ нужно выводить только существующие компании, ты же выводишь вообще все. Для этого можно использовать mapNotNull

2024-10-26 12:19 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson13/lesson13_task3.kt
> +    phoneList.forEach { println(it.company) }
Аааа... Недопонял

2024-10-27 06:04 UTC, ievetrovdev approved these changes

2024-10-27 06:26 UTC, merged