KS-14-5 chat done
JohnnyGomezzz/KotlinSprint pull request #73
Opened 2024-10-27 16:43 UTC by JohnnyGomezzz

2024-10-27 21:48 UTC, ievetrovdev requested changes

2024-10-27 21:48 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +    val ids: MutableList<Int> = (1..1000).toMutableList(),
Зачем делать лист, если это просто счетчик? Почему бы не прибавлять всегда +1, начиная с 1?

2024-10-28 07:20 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +    val ids: MutableList<Int> = (1..1000).toMutableList(),
Вот так можно?

2024-10-28 20:47 UTC, ievetrovdev approved these changes
Все верно, молодец!

2024-10-29 06:10 UTC, merged