KS-15-2 weather data sent to server
JohnnyGomezzz/KotlinSprint pull request #75
Opened 2024-10-28 19:29 UTC by JohnnyGomezzz

2024-10-29 17:46 UTC, ievetrovdev requested changes

2024-10-29 17:46 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +    val dayTemperature: Int = 0,
Этот класс является базовым для всех классов с погодными условиями и не должен иметь полей

2024-10-29 17:46 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +    fun getTemperatureFromStation(dayTemperature: Int, nightTemperature: Int): String {
Здесь должен быть один метод, который отправляет сообщение в зависимости от типа
Это довольно популярный паттерн, когда на входе у метода базовый тип данных, а внутри в зависимости от конкретного типа, разное поведение. Этот паттерн еще называют "Команда": https://refactoring.guru/ru/design-patterns/command

2024-10-30 18:24 UTC, ievetrovdev requested changes

2024-10-30 18:24 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +    abstract fun sendData()
Не совсем так, данные не отправляют сами себя, этот метод должен быть у сервера, который принимает данные, базовым типом которых является `WeatherStationStats`

2024-11-01 16:49 UTC, ievetrovdev requested changes

2024-11-01 16:49 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +class WeatherServer {
Не совсем так, должно выглядеть примерно так
```
class WeatherServer {
    fun sendMessage(weatherData: WeatherStationStats) {
        when (weatherData) {
            is Temperature ->
```

2024-11-01 19:46 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +class WeatherServer {
Получается вот так? Но это не похоже на то, что пишут про паттерн "Команда". Или я просто не умею упрощать...

2024-11-02 15:04 UTC, ievetrovdev approved these changes

2024-11-02 15:28 UTC, merged