KS-16-5 player-fighter done
JohnnyGomezzz/KotlinSprint pull request #83
Opened 2024-10-30 11:40 UTC by JohnnyGomezzz

2024-10-31 22:08 UTC, ievetrovdev requested changes

2024-10-31 22:08 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +        if (currentHealth <= 0) death()
Персонажа заставляют умереть при каждом получении урона. Надо бы вынести вызов этой функции в отдельное условие

2024-11-01 23:42 UTC, ievetrovdev requested changes

2024-11-01 23:42 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +        if (currentHealth <= 0) death()
Это не решает проблему, ведь смерть будет наступать, каждый раз, когда здоровье будет меньше 0. То есть, после первой смерти, новый урон снова вызовет смерть и тд, ведь здоровье будет ниже 0

2024-11-02 07:56 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +        if (currentHealth <= 0) death()
Ааааааа, допёрло...

2024-11-02 19:30 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-11-03 20:34 UTC, merged