KS-lesson2-3 train arrival time
JohnnyGomezzz/KotlinSprint pull request #9
Opened 2024-10-05 19:22 UTC by JohnnyGomezzz

2024-10-06 18:46 UTC, ievetrovdev requested changes
По поводу неймингов отписывал ранее

2024-10-06 18:46 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    println("Время прибытия: $arrivalHours:$arrivalMinutes")
Чтобы не писать нагруженных условий, рекомендую применить форматирование строк через String.format

2024-10-06 18:46 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    var arrivalHours = ((totalTime / TIME_UNITS) % 24).toString()
Давай 24 вынесем в константу, это [магическое число](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования), что не является хорошей практикой.

2024-10-07 17:02 UTC, ievetrovdev requested changes

2024-10-07 17:02 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +            "Время прибытия: %s:%s",
Для добавления 0 в начало есть специальный паттерн: `"%02d:%02d"`

2024-10-07 17:23 UTC, JohnnyGomezzz commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +            "Время прибытия: %s:%s",
Спасибо)

2024-10-07 19:17 UTC, ievetrovdev approved these changes

2024-10-07 19:36 UTC, merged